jobs:

  build:
     runs-on: ubuntu-latest


     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
 
     - name: SonarCloud Scan
       run: mvn -B verify  sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=sastlab-Dsonar.projectKey=javaprojectlab -Dsonar.login=$SONAR_TOKEN
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
